version: '3.8'
services:
    front-end:
        build:
            context: ./front-end
            dockerfile: Dockerfile
        image: softy-pinko-front-end
        ports:
            - "9000:80"
        depends_on:
            - back-end

    back-end:
        build:
            context: ./back-end
            dockerfile: Dockerfile
        image: softy-pinko-back-end
        ports:
            - "5252:5252"
